name: "test"
on: workflow_dispatch
jobs:
  before:
    runs-on: ubuntu-latest
    steps:
    - name: echo var
      run: echo ${{vars.VERSION}}
  edit:
    runs-on: ubuntu-latest
    steps:
    - name: Edit Variable
      run: |
        curl -L \
        -X PATCH \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/f4n0/TestActions/actions/variables/VERSION \
        -d '1.0.3'
  post:
    runs-on: ubuntu-latest
    steps:
    - name: echo var post
      run: echo ${{vars.VERSION}}
