name: "test"
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo var pre
        run: echo ${{vars.VERSION}}
  
      - name: modify var
        run: echo "VERSION=1.0.1" >> "$GITHUB_VARS"

      - name: echo var post
        run: echo ${{vars.VERSION}}
