name: "test"
on: workflow_dispatch
jobs:
  before:
    runs-on: ubuntu-latest
    steps:
    - name: echo var
      run: echo ${{vars.VERSION}}
  edit:
    runs-on: ubuntu-latest
    needs: before
    steps:
    - name: Edit Variable
      run: |
        NEWVER=$(echo ${{vars.VERSION}} | awk -F. -v OFS=. '{$NF += 1; print}')
        curl -L \
        -X PATCH \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.VARIABLES }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        -d '{"name":"VERSION","value":"'"$NEWVER"'"}' \
        https://api.github.com/repos/f4n0/TestActions/actions/variables/VERSION 
  post:
    runs-on: ubuntu-latest    
    needs: edit
    steps:
    - name: echo var post
      run: echo ${{vars.VERSION}}
