name: "test"
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo var pre
        run: echo ${{vars.VERSION}}
  
      - name: modify var
        uses: mmoyaferrer/set-github-variable@v1.0.0
        with:
            name: 'VERSION'
            value: '1.0.1'
            repository: f4n0/TestActions
            token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: echo var post
        run: echo ${{vars.VERSION}}
